# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-07 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0003_auto_20200507_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(default='rooms_folder/no-img.jpg', upload_to=b''),
        ),
    ]
