# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0004_auto_20200507_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_image',
        ),
    ]
