# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0005_remove_room_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(default='rooms_folder/no-img.jpg', upload_to=b''),
        ),
    ]
