# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 07:08
from __future__ import unicode_literals

import chat_room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0006_room_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=chat_room.models.roomImageFile),
        ),
    ]
